// app/layout.tsx  (Server Component — do NOT add "use client")
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
// ✅ Locomotive CSS import yahi pe
import "locomotive-scroll/dist/locomotive-scroll.css";

import AppShell from "@/components/AppShell";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brandelo - Your Digital Growth Partner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black text-black dark:text-white`}
      >
        {/* AppShell is a CLIENT component that will:
            1. Show the animated Brandelo splash first
            2. Then reveal Navbar + page + Footer */}
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
